### ISSUE TITLE
[Feature Request]: Register Product Stock Items by Rental Business Employees

### ISSUE THREAD

**Issue by mariodavid** [mariodavid/rent-your-stuff#10]
### Feature description

As a Rental Business Employee
I want to register new stock items for a product with unique identifiable information
So that I can offer those stock items for rental to customers.

**Comment by mariodavid** [comment]
## TODOs

- [x] create stock item entity
- [x] assign stock items to products
- [x] store identifiable information to stock items, like license plate information, serial numbers, etc.
