### ISSUE TITLE
[Feature Request]: Organise Products in Product Categories by Rental Business Employees

### ISSUE THREAD

**Issue by mariodavid** [mariodavid/rent-your-stuff#11]
### Feature description

As a Rental Business Employees
I want to manage product categories and group products in categories
So that customers have a better overview of the different kinds of products I offer.

**Comment by mariodavid** [comment]
## TODOs

- [x] create ProductCategory entity
- [x] managed product categories through the UI
- [x] create optional association between products and product categories
