### ISSUE TITLE
[Feature Request]: Support multiple Rental businesses on the Platform by Rent-Your-Stuff Ltd.

### ISSUE THREAD

**Issue by mariodavid** [mariodavid/rent-your-stuff#12]
### Feature description

As Rent-Your-Stuff Ltd.
we want to offer Rent-Your-Stuff to multiple Rental businesses
So that I can offer Rent-Your-Stuff at a lower price per customer.

**Comment by mariodavid** [comment]
## TODOs

- [x] enable multi-tenancy within the application
- [x] make User entity & management UI tenant aware
- [x] Change Login screen to support multi tenancy
- [x] make business entities tenant aware
