### ISSUE TITLE
[Feature Request]: Create a Rental Order

### ISSUE THREAD

**Issue by mariodavid** [mariodavid/rent-your-stuff#39]
### Feature description

As a Rental Business Employee
I want to create an order on stock items for a particular customer
So that I can rent my stuff.

**Comment by mariodavid** [comment]
## TODOs: Data Model

- [x] create Order entity
- [x] create OrderLine entity
- [x] associate with Customer & StockItem

**Comment by mariodavid** [comment]
## TODOs: Data Model Tests

- [x] create Order Validation Test
- [x] create OrderLine Validation Test
- [x] create Validation for valid rental period
- [x] refactor Validation tests
- [x] create Instance Name Test for Order
- [x] refactoring test data
- [x] create Order Storage Test

**Comment by mariodavid** [comment]
## TODOs: UI

- [x] create standard UI for managing orders
