### ISSUE TITLE
[Feature Request]: Show Customer Details after selection during Order creation

### ISSUE THREAD

**Issue by mariodavid** [mariodavid/rent-your-stuff#47]
### Feature description

As a Rental Business Employee
I want to see the most important Customer details after selecting a particular customer in the order process
So that I have more context about the Customer during the order creation

**Comment by mariodavid** [comment]
## TODOs: Tests

- [x] ensure customer details are displayed after selecting customer
- [x] ensure customer details are displayed when opening existing order with customer association
- [x] ensure customer search is active after removing customer
