### ISSUE TITLE
[Feature Request]: Define Rental Period on Order instead of Order Item

### ISSUE THREAD

**Issue by mariodavid** [mariodavid/rent-your-stuff#49]
### Feature description

As a Rental Business Employee
I want to enter the rental period on the overall order instead of the order item
So that I can enter the rental period faster and don't have to deal with the complexity that multiple rental orders can have different periods in my business

**Comment by mariodavid** [comment]
### TODOs

- [x] add rental period to Order entity
- [x] migrate existing rental periods from OrderLine to Order entity
- [x] fix broken tests
- [x] create migration integration test for the rental period data migration
