### ISSUE TITLE
[Feature Request]: Create Products by Rental Business Employees

### ISSUE THREAD

**Issue by mariodavid** [mariodavid/rent-your-stuff#9]
### Feature description

As a Rental Business Employee
I want to create rental construction products (like mini excavators) with their general attributes
So that I can register stock items of this product for later rentals.

**Comment by mariodavid** [comment]
## TODOs

- [x] create product entity
- [x] store product information, like name, description, images
- [x] allow configuring flat pricing like 50 EUR / day, 80 EUR per week
